// Code generated by goctl. DO NOT EDIT.
package types

type ChatHisoryRequest struct {
	UserID   uint `header:"user_id"`
	Page     int  `form:"page,optional"`
	Limit    int  `form:"limit,optional"`
	FriendID uint `form:"friend_id"`
}

type ChatHisoryResponse struct {
	ID        uint   `json:"id"`
	UserID    uint   `json:"user_id"`
	Avatar    string `json:"avatar"`
	Nickname  string `json:"nickname"`
	CreatedAt string `json:"created_at"`
}

type ChatSession struct {
	UserID     uint   `json:"user_id"`
	Avatar     string `json:"avatar"`
	Nickname   string `json:"nickname"`
	CreatedAt  string `json:"created_at"`
	MsgPreview string `json:"msg_preview"`
	IsTop      bool   `json:"is_top"`
	IsOnline   bool   `json:"is_online"`
}

type ChatSessionRequest struct {
	UserID uint `header:"user_id"`
	Page   int  `form:"page,optional"`
	Limit  int  `form:"limit,optional"`
	Key    int  `form:"key,optional"`
}

type ChatSessionResponse struct {
	List  []ChatSession `json:"list"`
	Count int64         `json:"count"`
}

type ChatDeleteRequest struct {
	UserID uint   `header:"user_id"`
	IdList []uint `json:"id_list"`
}

type ChatDeleteResponse struct {
}

type ChatRequest struct {
	UserID uint `header:"user_id"`
}

type ChatResponse struct {
}

type UserToopResponse struct {
}

type UserTopRequest struct {
	UserID   uint `header:"user_id"`
	FriendID uint `json: "friend_id"`
}
