// Code generated by goctl. DO NOT EDIT.
package types

type AuthenticationRequest struct {
	Token    string `header:'Token,required'`    //token
	ValiPath string `header:'ValiPath,optional'` //验证路径
}

type AuthenticationResponse struct {
	UserID uint `json:"userid"` //用户ID
	Role   int  `json:"role"`   //角色
}

type LoginRequest struct {
	UserName string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
}

type LoginResponse struct {
	Token string `json:"token"` //登录成功后返回的token
}

type OpenLoginInfoRespone struct {
	Name string `json:"name"` //名称
	Icon string `json:"icon"` //图标
	Href string `json:"href"` //跳转链接
}

type OpenLoginRequest struct {
	Code string `json:"code"` //授权码
	Flag string `json:"flag"` //登录标识，区分登录类型
}
